services:
  db:
    image: postgres:15-alpine
    container_name: django_waitlist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=waitlist_db
    ports:
      - "5432:5432"
    networks:
      - waitlist_network

  web:
    build: .
    container_name: django_waitlist_app
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=waitlist_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - waitlist_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: django_waitlist_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - waitlist_network

volumes:
  postgres_data:

networks:
  waitlist_network:
    driver: bridge