# Generated by Django 6.0.3 on 2026-03-18 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(help_text='Enter your phone number with country code (e.g., +254...)', max_length=20)),
                ('business_name', models.CharField(help_text='Enter your business name', max_length=200)),
                ('business_type', models.CharField(choices=[('ISP', 'ISP'), ('GYM', 'Gym'), ('SACCO', 'Sacco'), ('CHAMA', 'Chama'), ('OTHER', 'Other')], default='OTHER', help_text='Select your business type', max_length=20)),
                ('other_business_description', models.CharField(blank=True, help_text="If you selected 'Other', please specify your business industry", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
